version: '3'

networks:
  app-network:
    driver: bridge

services:
  web:
    build: ./back/web
    ports:
      - "8000:1111"   # Проброс порта: хост 8000 → контейнер 1111
    command: uvicorn project.main:app --host 0.0.0.0 --port 1111
    volumes:
      - ./back/web:/usr/src/app
      - ./back/dist/static:/usr/src/dist/static
#      - ./back/web:/code
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: ./back/dist
#    build: ./back/nginx
    ports:
      - "80:80"
    volumes:
      - ./back/dist/static:/usr/src/dist/static
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: diplom_project
    networks:
      - app-network
