name: Python CI/CD

on:
  push:
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/dev-requirements.txt
      - name: Lint with flake8
        run: flake8 src || true
      - name: Format check with Black
        run: black --check src/ || true
      - name: Import sorting check with isort
        run: isort --check-only src/ || true

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/dev-requirements.txt

      - name: Run tests with pytest
        run: pytest --cov=project tests/
